import type { PageManifestEntry } from "../content/page-types";

export const pageManifest = [
  {
    id: "home",
    path: "/",
    family: "home",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Tri-Cities WA Photographer | It's A Keeper Photography",
    summary: "Warm, natural portraits across Richland, Kennewick and Pasco.",
  },
  {
    id: "family",
    path: "/family-photographer-tri-cities-wa/",
    contentPath: "family.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Family Photographer Tri-Cities WA | Golden-Hour Sessions",
    summary: "Relaxed, golden-hour family photography in the Tri-Cities.",
  },
  {
    id: "seniors",
    path: "/senior-photographer-tri-cities-wa/",
    contentPath: "seniors.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "arch",
    title: "Senior Pictures Tri-Cities WA | It's A Keeper Photography",
    summary: "Confident, natural senior pictures photographed in golden light.",
  },
  {
    id: "newborn",
    path: "/newborn-photographer-tri-cities-wa/",
    contentPath: "newborn.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "Newborn Photographer Tri-Cities WA | Gentle Sessions",
    summary: "Gentle, baby-led newborn photography in the Tri-Cities.",
  },
  {
    id: "branding",
    path: "/branding-photographer-tri-cities-wa/",
    contentPath: "branding.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Branding Photographer Tri-Cities WA | Custom Business Photos",
    summary: "Personal branding photography for Tri-Cities businesses.",
  },
  {
    id: "headshots",
    path: "/headshot-photographer-tri-cities-wa/",
    contentPath: "headshots.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "arch",
    title: "Professional Headshots Tri-Cities WA | Natural & Confident",
    summary: "Natural professional headshots for Tri-Cities professionals and teams.",
  },
  {
    id: "investment",
    path: "/investment/",
    contentPath: "investment.json",
    family: "trust",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "Photography Session Investment | It's A Keeper Photography",
    summary: "What to expect before, during and after a portrait session with Lisa.",
  },
  {
    id: "about",
    path: "/about/",
    contentPath: "about.json",
    family: "trust",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "AboutPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "arch",
    title: "About Lisa Weiss | It's A Keeper Photography",
    summary: "Meet Lisa Weiss, the photographer behind It's A Keeper Photography.",
  },
  {
    id: "reviews",
    path: "/reviews/",
    contentPath: "reviews.json",
    family: "trust",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "Photography Reviews | Tri-Cities Families & Businesses",
    summary: "Client experiences with It's A Keeper Photography in the Tri-Cities.",
  },
  {
    id: "contact",
    path: "/contact/",
    contentPath: "contact.json",
    family: "trust",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "ContactPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Contact It's A Keeper Photography | Plan Your Session",
    summary: "Start planning a portrait session with Lisa in the Tri-Cities.",
  },
  {
    id: "richland",
    path: "/richland-wa-photographer/",
    contentPath: "richland.json",
    family: "city",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "arch",
    title: "Richland WA Photographer | It's A Keeper Photography",
    summary: "Golden-hour portrait photography in Richland, Washington.",
  },
  {
    id: "kennewick",
    path: "/kennewick-wa-photographer/",
    contentPath: "kennewick.json",
    family: "city",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Kennewick WA Photographer | It's A Keeper Photography",
    summary: "Golden-hour portrait photography in Kennewick, Washington.",
  },
  {
    id: "pasco",
    path: "/pasco-wa-photographer/",
    contentPath: "pasco.json",
    family: "city",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "Pasco WA Photographer | It's A Keeper Photography",
    summary: "Golden-hour portrait photography in Pasco, Washington.",
  },
  {
    id: "journal",
    path: "/journal/",
    contentPath: "journal.json",
    family: "journal-hub",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "CollectionPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Photography Journal | Tips & Locations From Lisa",
    summary: "First-hand portrait planning advice from a Tri-Cities photographer.",
  },
  {
    id: "locations-guide",
    path: "/journal/family-photo-locations-tri-cities/",
    contentPath: "journal-family-locations.json",
    family: "article",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "arch",
    title: "Best Places to Take Pictures in the Tri-Cities, WA",
    summary: "A photographer's guide to portrait locations across the Tri-Cities.",
  },
  {
    id: "senior-timing",
    path: "/journal/when-to-book-senior-pictures-tri-cities/",
    contentPath: "journal-senior-timing.json",
    family: "article",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "When to Take Senior Pictures | Tri-Cities Timeline",
    summary: "A practical booking timeline for Tri-Cities senior pictures.",
  },
  {
    id: "newborn-comparison",
    path: "/journal/in-home-vs-studio-newborn-photography/",
    contentPath: "journal-newborn-comparison.json",
    family: "article",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "In-Home vs Studio Newborn Photography | Which Is Right?",
    summary: "An honest comparison of in-home and studio newborn photography.",
  },
  {
    id: "branding-vs-headshots",
    path: "/journal/branding-photos-vs-headshots/",
    contentPath: "journal-branding-vs-headshots.json",
    family: "article",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "Branding Photos vs. Headshots: What's the Difference?",
    summary: "A plain-English comparison of branding photos and professional headshots.",
  },
  {
    id: "portfolio",
    path: "/portfolio/",
    family: "portfolio",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "CollectionPage",
    sitemap: true,
    llms: false,
    primaryRoute: false,
    signature: "overlap",
    title: "Photography Portfolio | It's A Keeper Photography",
    summary: "A page-turning portrait portfolio from It's A Keeper Photography.",
  },
  {
    id: "privacy",
    path: "/privacy/",
    contentPath: "privacy.json",
    family: "utility",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: false,
    llms: false,
    primaryRoute: false,
    signature: "crossing-line",
    title: "Privacy | It's A Keeper Photography",
    summary: "Privacy information for It's A Keeper Photography.",
  },
  {
    id: "thank-you",
    path: "/thank-you/",
    contentPath: "thank-you.json",
    family: "utility",
    contentStatus: "ready",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: false,
    llms: false,
    primaryRoute: false,
    signature: "arch",
    title: "Thank You | It's A Keeper Photography",
    summary: "A warm confirmation after sending an inquiry.",
  },
] as const satisfies readonly PageManifestEntry[];

export const editorialManifest = pageManifest.filter(
  (entry): entry is (typeof pageManifest)[number] & { contentPath: string } =>
    "contentPath" in entry
);

export const topLevelEditorialManifest = editorialManifest.filter(
  (entry) => entry.path.split("/").filter(Boolean).length === 1
);

export const journalArticleManifest = editorialManifest.filter(
  (entry) => entry.family === "article"
);

export const getManifestEntry = (path: string) => {
  const normalized = path === "/" ? "/" : `/${path.replace(/^\/+|\/+$/g, "")}/`;
  return pageManifest.find((entry) => entry.path === normalized);
};
