// CONTENT PENDING [/]: [PENDIENTE: el bloque actual menciona los health challenges de la hija de Lisa y la sesión con ganador de Grammy — confirmar con Lisa antes de reutilizar cualquiera de los dos aquí o en /about/]
// CONTENT PENDING [/]: [La cifra 96 debe verificarse al momento de publicar.]
// CONTENT PENDING [/about/]: [PENDIENTE: hobbies/detalles personales adicionales que Lisa quiera compartir — Q17 dijo "most of this", falta especificar. PENDIENTE: bloque de la hija/health challenges — confirmar publicación.]
// CONTENT PENDING [/about/]: [PENDIENTE: nombre del premio — Q10/Q42]
// CONTENT PENDING [/about/]: [PENDIENTE: MOM Magazine feature — Q42, con link]
// CONTENT PENDING [/about/]: [PENDIENTE: sesión con ganador de Grammy — Q43, con permiso]
// CONTENT PENDING [/about/]: [PENDIENTE: certificaciones, seguro, membresías — Q40–41]
// CONTENT PENDING [/about/]: [si se publica]
// CONTENT PENDING [/branding-photographer-tri-cities-wa/]: [PENDIENTE: entregables exactos, cantidad de imágenes, derechos de uso comercial — Q54, Q58]
// CONTENT PENDING [/branding-photographer-tri-cities-wa/]: [PENDIENTE: si Lisa ofrece membresía/paquete recurrente — hueco competitivo vs. JK Photos]
// CONTENT PENDING [/contact/]: [PENDIENTE: plazo habitual — Q50]
// CONTENT PENDING [/contact/]: [PENDIENTE: retainer/contrato — Q51]
// CONTENT PENDING [/family-photographer-tri-cities-wa/]: [PENDIENTE: 2–3 reseñas reales de familias, con nombre — Q47]
// CONTENT PENDING [/headshot-photographer-tri-cities-wa/]: [PENDIENTE: duración/formato exacto — Q54]
// CONTENT PENDING [/investment/]: [PENDIENTE: Q49–62 — paquetes, inclusiones, políticas exactas. Los bloques marcados se completan con las respuestas de Lisa.]
// CONTENT PENDING [/investment/]: [PENDIENTE: entrega — nº de imágenes, galería online, derechos de impresión, plazos — Q54, Q56, Q58]
// CONTENT PENDING [/investment/]: [PENDIENTE: tiempo de respuesta habitual — Q50]
// CONTENT PENDING [/investment/]: [PENDIENTE: turnaround — Q56]
// CONTENT PENDING [/investment/]: [PENDIENTE: retainer/contrato — Q51]
// CONTENT PENDING [/investment/]: [PENDIENTE: política exacta — Q55]
// CONTENT PENDING [/investment/]: [PENDIENTE: detalle — Q57]
// CONTENT PENDING [/investment/]: [PENDIENTE: Q51]
// CONTENT PENDING [/investment/]: [PENDIENTE: Q59 — si sí, párrafo sobre productos heirloom; encaja perfecto con la filosofía "photographs become heirlooms"]
// CONTENT PENDING [/journal/branding-photos-vs-headshots/]: [FECHA]
// CONTENT PENDING [/journal/family-photo-locations-tri-cities/]: [VALIDAR CON LISA — CRÍTICO]
// CONTENT PENDING [/journal/family-photo-locations-tri-cities/]: [LISA: detalle de primera mano]
// CONTENT PENDING [/journal/family-photo-locations-tri-cities/]: [LISA: confirmar acceso/permisos de los huertos que usa]
// CONTENT PENDING [/journal/family-photo-locations-tri-cities/]: [VALIDAR: normativa actual de City of Richland / Kennewick / Pasco parks para fotografía comercial — responder con dato verificado]
// CONTENT PENDING [/journal/family-photo-locations-tri-cities/]: [quién] + [locación con nombre] + [luz/estación]
// CONTENT PENDING [/journal/family-photo-locations-tri-cities/]: [FECHA]
// CONTENT PENDING [/journal/in-home-vs-studio-newborn-photography/]: [VALIDAR CON LISA]
// CONTENT PENDING [/journal/in-home-vs-studio-newborn-photography/]: [VALIDAR: formato exacto que ofrece Lisa]
// CONTENT PENDING [/journal/in-home-vs-studio-newborn-photography/]: [FECHA]
// CONTENT PENDING [/journal/when-to-book-senior-pictures-tri-cities/]: [VALIDAR: fechas concretas de los distritos de Richland, Kennewick y Pasco — dato local que nadie más publica]
// CONTENT PENDING [/journal/when-to-book-senior-pictures-tri-cities/]: [VALIDAR: si Lisa ofrece esto — Q54]
// CONTENT PENDING [/journal/when-to-book-senior-pictures-tri-cities/]: [FECHA]
// CONTENT PENDING [/kennewick-wa-photographer/]: [VALIDAR CON LISA: sus spots reales de Kennewick + 1–2 detalles de primera mano por locación]
// CONTENT PENDING [/kennewick-wa-photographer/]: [PENDIENTE: 6–10 imágenes de sesiones reales en Kennewick con alt text de locación]
// CONTENT PENDING [/kennewick-wa-photographer/]: [VALIDAR — Q53]
// CONTENT PENDING [/newborn-photographer-tri-cities-wa/]: [PENDIENTE: confirmar con Lisa formato exacto (in-home / lifestyle / outdoor para familias con newborn), y si menciona seguridad/posing seguro — Q41, Q63+]
// CONTENT PENDING [/pasco-wa-photographer/]: [VALIDAR CON LISA: sus spots reales de Pasco + detalles de primera mano]
// CONTENT PENDING [/pasco-wa-photographer/]: [PENDIENTE: 6–10 imágenes de sesiones reales en Pasco con alt text de locación]
// CONTENT PENDING [/pasco-wa-photographer/]: [VALIDAR — Q53]
// CONTENT PENDING [/privacy/]: [PENDIENTE: contenido legal de privacidad revisado y aprobado antes de publicar]
// CONTENT PENDING [/reviews/]: [PENDIENTE CRÍTICO: Q47 — selección de 8–12 reseñas reales de Google con permiso/nombres. La estructura queda lista; las citas de ejemplo son placeholders de las 3 del sitio actual.]
// CONTENT PENDING [/reviews/]: [link al perfil de Google]
// CONTENT PENDING [/reviews/]: [Nombre, Richland]
// CONTENT PENDING [/reviews/]: [PENDIENTE: +2 reseñas de familias]
// CONTENT PENDING [/reviews/]: [PENDIENTE: reseñas de seniors — priorizar las que mencionen confianza/comodidad y el reveal]
// CONTENT PENDING [/reviews/]: [PENDIENTE: reseñas newborn]
// CONTENT PENDING [/reviews/]: [PENDIENTE: reseñas de branding/headshots]
// CONTENT PENDING [/reviews/]: [link externo]
// CONTENT PENDING [/richland-wa-photographer/]: [VALIDAR CON LISA: confirmar que estos son SUS spots reales y añadir 1–2 detalles de primera mano por locación (p. ej. "la luz cae detrás de X a las Y"). Ese detalle es lo que ninguna otra página puede copiar.]
// CONTENT PENDING [/richland-wa-photographer/]: [PENDIENTE: 6–10 imágenes de sesiones reales en Richland, cada una con alt text que nombre la locación]
// CONTENT PENDING [/richland-wa-photographer/]: [VALIDAR: formato newborn]
// CONTENT PENDING [/richland-wa-photographer/]: [VALIDAR: política de viaje — Q2/Q53]
// CONTENT PENDING [/senior-photographer-tri-cities-wa/]: [PENDIENTE: dato de senior model/rep program si Lisa tiene o quiere uno — hueco competitivo vs. Kluse]
// CONTENT PENDING [/senior-photographer-tri-cities-wa/]: [PENDIENTE: número exacto según paquete — Q54]
