query portfolioPage(
  $homepagePath: String!
  $settingsPath: String!
  $journalPageLimit: Float!
) {
  homepage(relativePath: $homepagePath) {
    ...HomepageParts
  }
  settings(relativePath: $settingsPath) {
    ...SettingsParts
  }
  journalPageConnection(first: $journalPageLimit, sort: "order") {
    edges {
      node {
        _sys {
          relativePath
        }
        ...JournalPageParts
      }
    }
  }
}
